### ISSUE TITLE
The `set-env` command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by sebhoss** [rinx/setup-graalvm-ce#3]
It seems Github is deprecating the usage of `set-env` which is used in [entrypoint.sh](https://github.com/rinx/setup-graalvm-ce/blob/master/entrypoint.sh#L25). See https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/ for details.

**Comment by rinx** [comment]
@sebhoss Thanks for reporting the issue.
I've just fixed the problem and publish a new release v0.0.5 (https://github.com/rinx/setup-graalvm-ce/releases/tag/v0.0.5).

**Comment by sebhoss** [comment]
Thanks a lot!
